---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: PivotalDevOpsTutorial
- name: current-app-info

run:
  path: ci/tasks/load-tests
