---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: PivotalDevOpsTutorial

run:
  path: PivotalDevOpsTutorial/ci/tasks/run-unit-tests
