---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: concourse-pipeline-samples
- name: current-app-info

run:
  path: ci/tasks/update-routes
